# Generated by Django 5.2.3 on 2025-06-29 14:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название акции"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "discount_percent",
                    models.PositiveIntegerField(verbose_name="Скидка (%)"),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна?"),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-start_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=100, verbose_name="Имя гостя"),
                ),
                (
                    "guest_phone",
                    models.CharField(max_length=20, verbose_name="Телефон гостя"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество гостей"
                    ),
                ),
                ("time_start", models.DateTimeField(verbose_name="Время начала брони")),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=10800),
                        help_text="По умолчанию 3 часа. Меняется только админом",
                        verbose_name="Длительность брони",
                    ),
                ),
                (
                    "extended_by_admin",
                    models.BooleanField(default=False, verbose_name="Продлена вручную"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("guest", "Гость через сайт"),
                            ("admin", "Администратор вручную"),
                        ],
                        default="guest",
                        help_text="Кем оформлена бронь (определяется автоматически)",
                        max_length=20,
                        verbose_name="Источник брони",
                    ),
                ),
                (
                    "upsell_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text=" Сумма в рублях за доп продажу",
                        verbose_name="Апсейл: Дополнительный доход (в рублях)",
                    ),
                ),
                (
                    "upsell_option",
                    models.CharField(
                        blank=True,
                        help_text="Тип допродажи: десерт, зона, декор и т.п.",
                        max_length=100,
                        null=True,
                        verbose_name="Апсейл-опция",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Уникальный код: T1, VIP-2, Окно 3",
                        max_length=20,
                        unique=True,
                        verbose_name="Номер столика",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Отображается на карте зала: 'Окно 4', 'Центр'",
                        max_length=50,
                        null=True,
                        verbose_name="Название для отображения",
                    ),
                ),
                (
                    "seats_total",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество мест за столом"
                    ),
                ),
                (
                    "x",
                    models.PositiveIntegerField(default=0, verbose_name="Координата X"),
                ),
                (
                    "y",
                    models.PositiveIntegerField(default=0, verbose_name="Координата Y"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Свободен"),
                            ("unavailable", "Недоступен"),
                        ],
                        default="available",
                        help_text="Вычисляется автоматически на основе бронирований",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["seats_total", "number"],
            },
        ),
    ]
