# Generated by Django 5.2.3 on 2025-07-02 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="upsell_option",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите дополнительную опцию из списка активных акций",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.promotion",
                verbose_name="Апсейл-опция (Акция)",
            ),
        ),
    ]
